elasticsearch:
  image: elasticsearch

dev:
  dockerfile: Dockerfile.dev
  build: .
  command: mix help
  links:
    - elasticsearch
  volumes:
    - .:/code
    - .hex:/root/.hex
    - .mix:/root/.mix
  environment:
    - MIX_ENV=test
